Major rework.
WebStandardsFuture/Vision pull request #9
Opened 2021-02-25 17:12 UTC by cwilso

Tightened up the intro, streamlined radically, moved history to the end prior to moving it to a separate doc.  Began rationalizing against strategy wiki.

2021-02-25 17:47 UTC, cwilso commented
I should have explicitly noted here - this PR is the result of much collaboration between @tantek and myself; it is not solely my work by a long shot.

2021-02-25 20:21 UTC, cwilso commented on README.md
> +
I wanted this to be more focused on a specific change in the mission - not just that it's a change, but that we want to change to focus on improving the integrity of the web. (as further described in the points below.)

I'm happy to further wordsmith this, but can we proceed with this change for now and do so separately?

2021-02-25 20:27 UTC, dwsinger commented on README.md
> +
OK. Then something like "Vision: the Web built on values" or "Vision: Re-basing the Web on values". We're trying to express a compelling vision for the future, and I fear that this title under-sells that. "New" suggests that there are old foci (and maybe they still exist), "focus" isn't as strong a vision. Not a huge deal but I think we can improve

2021-02-25 20:58 UTC, tantek commented on README.md
> +
Agreed that we can improve with a more compelling title. I think this is a good enough improvement to land and then further iterate. @dwsinger would you be open to opening an issue on this, something like: stronger Vision title / one-liner?

2021-02-25 21:01 UTC, tantek approved these changes
Having worked on this, and reviewed the comments, I think this is good to land as a net improvement and then continue iterating, especially with editorial fixes.

2021-02-25 21:20 UTC, michaelchampion commented on README.md
> +
I tend to agree with Dave ; there are 9 points that could use some organization to make the document more compelling.  For example I see 3 major categories: Vision for the web itself, Goals for W3C in pursuing that vision, and Principles W3C must adhere to while pursuing the goals.

Here's an attempt to refactor the 9 points into the 3 categories; each category probably needs some explanatory text:

Vision for the web
- The web should work for everyone
- Its fundamental principles : accessibility, internationalization, security, and privacy (openness?  interoperability?)
-
W3C's program to achieve those goals:

- driving interoperability across vendors and implementations using open test suites
- fostering collaboration and interoperability with a strong patent policy and open licenses
- encouraging incubation in new areas & industries with platforms for discussion & collaboration
- building mutually respectful relationships with governments
- revisiting the current Web platform and exploring how to responsibly improve personal privacy, as well as assessing privacy and security impacts of new capabilities, user scenarios, and innovations relationships with governments & businesses for providing credible advice.
- 
Principles while pursuing them:
- putting the needs of users first: above authors, publishers, implementers, paying W3C Members, or theoretical purity; a priority of constituencies built on the excellent work from the TAG's Ethical Web Principles and the HTML Design Principles.
- striving for diversity & inclusion of participants from different geographical locations, gender identities, accessibility needs, and more.

2021-02-25 21:22 UTC, michaelchampion commented on README.md
Agree it is a bit run-on.  Not sure if it needs bullets or just shorter sentences.

2021-02-25 21:33 UTC, michaelchampion requested changes
The only one of my comments (which echoes one of Dave's) that I feel strongly about is organizing the 9 bullet points under "Our Principles:" in "punchier" way.  9 points is too many -- see  https://en.wikipedia.org/wiki/Rule_of_three_(writing) and https://en.wikipedia.org/wiki/The_Magical_Number_Seven,_Plus_or_Minus_Two 

Most of the points are good, although some wordsmithing would help to reduce redundancy, all they really need is to be elaborations of a smaller number of high level points rather than a list of all sorts of stuff.

2021-02-25 23:36 UTC, michaelchampion approved these changes

2021-02-26 00:05 UTC, dwsinger approved these changes

2021-02-26 00:05 UTC, merged